jobs:
  include:
    - os: linux
      dist: focal
      language: python
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: 
          secure: gX7A3Qv+EwVs+FPzhqO4NH8CgDcUleEiqiE3lBJGcrQrosdIYyZHgnpwZraRBbyJImlC097+bmuFLG0wmZtr+708XnRqcUzrl+2tWIz5dJyAbYbTa48qtYz5floCSz5UHe7CuZ8xlLYZ6upLN6NaDUBiMYL6xkABtCVVF2FVxd44uWfhEwm2dUNL+Len5KzWp3pkyQHEMAUvlvSkBOJ7pamxr5MJUAqNZKFQKe4YgsGrpCNW4cq4FwsYFAEMD4wrz42TLqrkOAZbSqFKt7JSDILvAbV+P2SI7BMQ2nxsPdvPbDl1yEGfUmZDNy/aVZpXYU2gSqj3bPQ9uutBLf70l4Ju7L+AaEaTpl2NlCSWNE2Nq1dvxvFCHriqX+w9j88vHB8bNJBJYzkhYZC4t9mBVV44N8YQlXV9z+uxGybiTyF7K7SKlbrfZ2rOXsOpjdOh7Xp9zSBB210H2LYVPNn3iha4a1Esk+0TWOP0B20jvVBTIvRcFgx/+xhhMwBzZUeZUV9Y0X+igoMRhugSgSCmFqz2moDpy6Bs4ZqwkBoGfoKPSJ7DaiarhaipSEwqwk3xSALWDONsAB4TYDWLNSJmZ2NkDdkpiE82TQjuOE4aKF75gElLo9Ruu14Sihe7RfVJl+eSuLXgwjRHkz5fjG0s26rHstIE0MdRWTBI3b0IpQo=
        secrets:
          - kv_api_ver: kv2
          - namespace:
            - name: ns1
            - language_used
          - ns1/two_tokens
      script:
        - echo $LANGUAGE_USED
        - echo $TWO_TOKENS
        - python hello_world.py

    - os: linux
      dist: bionic
      language: python
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: 
          secure: secure: gX7A3Qv+EwVs+FPzhqO4NH8CgDcUleEiqiE3lBJGcrQrosdIYyZHgnpwZraRBbyJImlC097+bmuFLG0wmZtr+708XnRqcUzrl+2tWIz5dJyAbYbTa48qtYz5floCSz5UHe7CuZ8xlLYZ6upLN6NaDUBiMYL6xkABtCVVF2FVxd44uWfhEwm2dUNL+Len5KzWp3pkyQHEMAUvlvSkBOJ7pamxr5MJUAqNZKFQKe4YgsGrpCNW4cq4FwsYFAEMD4wrz42TLqrkOAZbSqFKt7JSDILvAbV+P2SI7BMQ2nxsPdvPbDl1yEGfUmZDNy/aVZpXYU2gSqj3bPQ9uutBLf70l4Ju7L+AaEaTpl2NlCSWNE2Nq1dvxvFCHriqX+w9j88vHB8bNJBJYzkhYZC4t9mBVV44N8YQlXV9z+uxGybiTyF7K7SKlbrfZ2rOXsOpjdOh7Xp9zSBB210H2LYVPNn3iha4a1Esk+0TWOP0B20jvVBTIvRcFgx/+xhhMwBzZUeZUV9Y0X+igoMRhugSgSCmFqz2moDpy6Bs4ZqwkBoGfoKPSJ7DaiarhaipSEwqwk3xSALWDONsAB4TYDWLNSJmZ2NkDdkpiE82TQjuOE4aKF75gElLo9Ruu14Sihe7RfVJl+eSuLXgwjRHkz5fjG0s26rHstIE0MdRWTBI3b0IpQo=
        secrets:
          - ns2/project_id/secret_key_b
      script:
        - echo $SECRET_KEY_B
        - python hello_world.py
