jobs:
  include:
    - os: linux
      dist: focal
      language: python
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: 
          secure: gX7A3Qv+EwVs+FPzhqO4NH8CgDcUleEiqiE3lBJGcrQrosdIYyZHgnpwZraRBbyJImlC097+bmuFLG0wmZtr+708XnRqcUzrl+2tWIz5dJyAbYbTa48qtYz5floCSz5UHe7CuZ8xlLYZ6upLN6NaDUBiMYL6xkABtCVVF2FVxd44uWfhEwm2dUNL+Len5KzWp3pkyQHEMAUvlvSkBOJ7pamxr5MJUAqNZKFQKe4YgsGrpCNW4cq4FwsYFAEMD4wrz42TLqrkOAZbSqFKt7JSDILvAbV+P2SI7BMQ2nxsPdvPbDl1yEGfUmZDNy/aVZpXYU2gSqj3bPQ9uutBLf70l4Ju7L+AaEaTpl2NlCSWNE2Nq1dvxvFCHriqX+w9j88vHB8bNJBJYzkhYZC4t9mBVV44N8YQlXV9z+uxGybiTyF7K7SKlbrfZ2rOXsOpjdOh7Xp9zSBB210H2LYVPNn3iha4a1Esk+0TWOP0B20jvVBTIvRcFgx/+xhhMwBzZUeZUV9Y0X+igoMRhugSgSCmFqz2moDpy6Bs4ZqwkBoGfoKPSJ7DaiarhaipSEwqwk3xSALWDONsAB4TYDWLNSJmZ2NkDdkpiE82TQjuOE4aKF75gElLo9Ruu14Sihe7RfVJl+eSuLXgwjRHkz5fjG0s26rHstIE0MdRWTBI3b0IpQo=
        secrets:
          - kv_api_ver: kv2
          - namespace:
            - name: ns1
            - language_used
          - ns1/two_tokens
      script:
        - echo $LANGUAGE_USED
        - echo $TWO_TOKENS
        - python hello_world.py

    - os: linux
      dist: bionic
      language: python
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: 
          secure: "ehzimvuK0JC6S3iMGuDJm7EJeLu6or3SS2H0o7Ohrp80DithmPqkFx3XFqHZmiKPa4DVMBO09Y/AUO8Vdb6HS3cZS4OxmIBiUcCiV65NxWrOVNpNcIb+WD9RUQ9RWpjqEDqDblu2bD9s0EnZUsMDl5vh9lHpKF702i+bHuDpenXvrsYrmLKYn3K9LoH4OTqsWAirEl5AjR4V0DQrEXHv9U+YnIMGuOqRstQOfIx/MntCasBk8msR0smPyr5LU76BBoRXjwAGREt8XENJk7hd0tYwlFbHL964HmdIDwXVT2uXu4mTUnQd4Du+ZawosjuGx919SzS9NHrZQtXRk8HLfO1Zx57fgdTdgm99BsxEu/AQCZqvcWEeZJaCbahc9m0npjfnhDd2ZbVqs3ejK6UPzRfHwXWtf5OLlVFx2aK8RvNIBzxES10uV251xrn/9MIAgA+OHuxyfZUp+hXqZIEteZdw1Q/HY5sAjVBxPuVKj5Mu9woPXyfxsJfx0Xo27BuAdDCBR5s6Ek1kT64UHxuAgYFKqKP7yIZvGzIQEF/+OESh8blgSj5YqIsNhBQvGr13BoqhNddvcQnJaFXZcQvclW+MawM3l0AN+TEbZUdnki4MwaNRAu480FfFXa38sUsHcLslfsMUxR3TOtSJPs29POFOYBGJXca2tOT0yzJ+da0="
        secrets:
          - ns2/project_id/secret_key_b
      script:
        - echo $SECRET_KEY_B
        - python hello_world.py
